# Generated by Django 3.0.8 on 2020-09-04 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'Lcation', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Lcation', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_current_location', to='api.Locations', verbose_name='user current location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_last_location', to='api.Locations', verbose_name='user last location'),
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Calendar created at'),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Food name'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant', verbose_name='Restaurant name'),
        ),
        migrations.AddField(
            model_name='food',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Clendar updated at'),
        ),
        migrations.AddField(
            model_name='locations',
            name='city',
            field=models.CharField(max_length=80, null=True, verbose_name='City name'),
        ),
        migrations.AddField(
            model_name='locations',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Location created at'),
        ),
        migrations.AddField(
            model_name='locations',
            name='lang',
            field=models.CharField(max_length=50, null=True, verbose_name='Lang'),
        ),
        migrations.AddField(
            model_name='locations',
            name='lat',
            field=models.CharField(max_length=50, null=True, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='locations',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Location updated at'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Location created at'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='number',
            field=models.FloatField(null=True, verbose_name='number of reviews'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant', verbose_name='reviewed restaurant'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Location updated at'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who reviewed'),
        ),
        migrations.AlterField(
            model_name='restaurantcalendar',
            name='day',
            field=models.CharField(choices=[('Su', 'Sunday'), ('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday')], default='Su', max_length=5, verbose_name='Day'),
        ),
    ]
