# Generated by Django 3.0.8 on 2020-09-04 10:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200904_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageField', models.ImageField(upload_to='photos/', verbose_name='image field')),
            ],
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Restaurant created at'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Locations', verbose_name='Restaurant location'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Restaurant name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rank',
            field=models.IntegerField(default=-1, verbose_name='Restaurant rank'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_open',
            field=models.BooleanField(default=False, verbose_name='Restaurant boolean'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(max_length=250, null=True, verbose_name='Restaurant type'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Restaurant updated at'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photos',
            field=models.ManyToManyField(to='api.Photos', verbose_name='Restaurant photos'),
        ),
    ]
