# Generated by Django 3.0.8 on 2020-09-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_restaurantpromotion_restraurantcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='RestraurantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant', verbose_name='reviewed restaurant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reviews', verbose_name='retaurant review')),
            ],
            options={
                'verbose_name': 'Restaurant Review',
                'verbose_name_plural': 'Restaurants Reviews',
            },
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Food', verbose_name='reviewed food')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reviews', verbose_name='food review')),
            ],
            options={
                'verbose_name': 'Food Reiview',
                'verbose_name_plural': 'Foods Reviews',
            },
        ),
        migrations.AddField(
            model_name='restraurantcomments',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RestraurantReview', verbose_name='resturant review'),
        ),
    ]
