# Generated by Django 3.0.8 on 2020-09-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200905_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='api.Photos', verbose_name='Restaurant photos'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_open',
            field=models.BooleanField(default=False, verbose_name='Restaurant is open now'),
        ),
    ]
