# Generated by Django 3.0.8 on 2020-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200907_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.ManyToManyField(max_length=250, null=True, related_name='restaurant_services', to='api.RestaurantType', verbose_name='Restaurant type'),
        ),
    ]
