# Generated by Django 3.0.8 on 2020-09-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200907_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.ManyToManyField(default=None, max_length=250, related_name='restaurant_services', to='api.RestaurantType', verbose_name='Restaurant type'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='services',
            field=models.ManyToManyField(blank=True, default=None, to='api.RestaurantService', verbose_name='Restraurant services'),
        ),
    ]
