# Generated by Django 3.0.8 on 2020-09-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200907_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.ManyToManyField(blank=True, max_length=250, related_name='restaurant_services', to='api.RestaurantType', verbose_name='Restaurant type'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.RestaurantService', verbose_name='Restraurant services'),
        ),
    ]
