# Generated by Django 3.0.8 on 2020-09-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200907_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='foodreview',
            name='restaurant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant', verbose_name='restaurant name'),
        ),
    ]
