# Generated by Django 3.0.8 on 2020-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200907_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='total_review',
            field=models.IntegerField(default=0, verbose_name='total restaurant reviews'),
        ),
    ]
