# Generated by Django 3.0.8 on 2020-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_restaurant_total_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Restaurant image '),
        ),
    ]
