# Generated by Django 3.0.8 on 2020-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_restaurant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(blank=True, to='api.Food', verbose_name='Restraurant foods'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_review',
            field=models.IntegerField(default=0, verbose_name='Total restaurant reviews'),
        ),
    ]
