# Generated by Django 3.0.8 on 2020-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200907_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Food image '),
        ),
    ]
