# Generated by Django 3.0.8 on 2020-09-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_food_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(null=True, upload_to='food/photos', verbose_name='Food image '),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(null=True, upload_to='resturant/photos/<django.db.models.fields.CharField>/', verbose_name='Restaurant image '),
        ),
    ]
