# Generated by Django 3.0.8 on 2020-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200914_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantservice',
            name='choice',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Restaurant service name'),
        ),
        migrations.AlterField(
            model_name='restauranttype',
            name='choice',
            field=models.CharField(max_length=125, primary_key=True, serialize=False, verbose_name='Restaurant type name'),
        ),
    ]
