# Generated by Django 3.0.8 on 2020-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200914_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantservice',
            name='slug',
            field=models.SlugField(max_length=500, null=True, verbose_name='Restaurant Service slug'),
        ),
        migrations.AddField(
            model_name='restauranttype',
            name='slug',
            field=models.SlugField(max_length=500, null=True, verbose_name='Restaurant Type slug'),
        ),
    ]
