# Generated by Django 3.0.8 on 2020-09-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_restaurant_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(null=True, verbose_name='Food description'),
        ),
    ]
