# Generated by Django 3.0.8 on 2020-09-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200918_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, verbose_name='Restaurant slug'),
        ),
    ]
