# Generated by Django 3.0.8 on 2020-09-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200918_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestraurantComments',
            new_name='RestaurantComments',
        ),
    ]
