# Generated by Django 3.0.8 on 2020-09-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200921_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantcomments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
