# Generated by Django 3.0.8 on 2020-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200922_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replys',
        ),
        migrations.AddField(
            model_name='comment',
            name='replys',
            field=models.ManyToManyField(blank=True, related_name='_comment_replys_+', to='api.Comment', verbose_name='Comment replys'),
        ),
    ]
