# Generated by Django 3.0.8 on 2020-09-30 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200924_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.CreateModel(
            name='ReastaurantCommentsUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Comment created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Comment updated at')),
                ('restaurant_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RestaurantComments', verbose_name='restaurant comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who cote up on comment')),
            ],
            options={
                'verbose_name': 'Restaurant comment up',
                'verbose_name_plural': 'Restaurants comments up',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReastaurantCommentsDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Comment created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Comment updated at')),
                ('restaurant_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RestaurantComments', verbose_name='Restaurant comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who cote up on comment')),
            ],
            options={
                'verbose_name': 'Restaurant comment down',
                'verbose_name_plural': 'Restaurants comments down',
                'ordering': ['-created_at'],
            },
        ),
    ]
