# Generated by Django 3.0.8 on 2020-10-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200930_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcomments',
            name='downs',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of downs in comment'),
        ),
        migrations.AddField(
            model_name='restaurantcomments',
            name='ups',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of ups in comment'),
        ),
        migrations.AddConstraint(
            model_name='reastaurantcommentsdown',
            constraint=models.UniqueConstraint(fields=('restaurant_comments', 'user'), name='unique_dow_comment_voting'),
        ),
        migrations.AddConstraint(
            model_name='reastaurantcommentsup',
            constraint=models.UniqueConstraint(fields=('restaurant_comments', 'user'), name='unique_up_comment_voting'),
        ),
    ]
