# Generated by Django 3.0.8 on 2020-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20201004_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcomments',
            name='downs',
            field=models.IntegerField(blank=True, default=0, verbose_name='number of downs in comment'),
        ),
        migrations.AlterField(
            model_name='restaurantcomments',
            name='ups',
            field=models.IntegerField(blank=True, default=0, verbose_name='number of ups in comment'),
        ),
    ]
