# Generated by Django 3.0.8 on 2020-10-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20201004_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantcomments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Restaurant Comment', 'verbose_name_plural': 'Reataurats Comments'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='total_review',
            field=models.FloatField(default=0, verbose_name='Total restaurant reviews'),
        ),
    ]
