# Generated by Django 3.0.8 on 2020-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20201011_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='number_of_reviews',
            field=models.IntegerField(default=0, verbose_name='Number of reviews'),
        ),
    ]
