# Generated by Django 3.0.8 on 2020-10-11 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_restaurant_number_of_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-created_at'], 'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-number_of_reviews', '-total_review'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.CreateModel(
            name='RestaurantUserFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Comment created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Comment updated at')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant', verbose_name='already visited restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who visited the restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant user favorites',
                'verbose_name_plural': 'Restaurants users favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAlreadyVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Comment created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Comment updated at')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant', verbose_name='already visited restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who visited the restaurant')),
            ],
            options={
                'verbose_name': 'Already visited restaurant by user',
                'verbose_name_plural': 'Already visited restaurants by users',
                'ordering': ['-created_at'],
            },
        ),
    ]
