# Generated by Django 3.0.8 on 2020-10-12 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201011_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='user key'),
        ),
    ]
