# Generated by Django 3.0.8 on 2020-11-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_customuser_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-96.png', null=True, upload_to='picture_profile/', verbose_name='user profile pic'),
        ),
    ]
